name: Demo
on:
  push:
  pull_request:
  schedule:
    - cron: '30 5,17 * * *'

env:
  go-version: '~1.18.0'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v3
              with:
                go-version: ${{ env.go-version }}
            - run: go build .
            - run: go vet
            - name: 'go fmt'
              run: |-
                GO_FMT="$(gofmt -d .)"
                if [[ -z "$GO_FMT" ]]; then
                    echo "format sitene"
                    exit 1
                fi
            - run: go run .
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
            go-version: ${{ env.go-version }}
        - run: go test -v ./...
        - run: echo "${go-version}"
